# portfolio-wp-theme CircleCI 2.1 configuration file

version: 2.1

executors:
  deploy:
    docker:
      - image: circleci/python:3.7

job-references:
  mysql_image: &mysql_image circleci/mysql:8.0.0

  setup_environment: &setup_environment
    name: "Setup Environment Variables"
    command: |
      echo "export PATH=$HOME/.composer/vendor/bin:$PATH" >> $BASH_ENV
      source /home/circleci/.bashrc

  install_dependencies: &install_dependencies
    name: "Install Dependencies"
    command: |
      sudo apt-get update && sudo apt-get install subversion
      sudo -E docker-php-ext-install mysqli
      sudo sh -c "printf '\ndeb http://ftp.us.debian.org/debian sid main\n' >> /etc/apt/sources.list"
      sudo apt-get update && sudo apt-get install mysql-client-5.7

  test_job: &test_job
    environment:
      - WP_TESTS_DIR: "/tmp/wordpress-tests-lib"
      - WP_CORE_DIR: "/tmp/wordpress/"
    steps:
      - checkout
      - run: *setup_environment
      - run: *install_dependencies
      - run:
          name: "Install Tests environment"
          command: |
            # composer install
            composer global require "phpunit/phpunit=7.*"

            rm -rf $WP_TESTS_DIR $WP_CORE_DIR
            bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 << parameters.version >>

            git clone --branch 5.8.4 https://github.com/wp-premium/advanced-custom-fields-pro vendor/advanced-custom-fields-pro
      - run:
          name: "Run Tests"
          command: |
            # phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
            # phpcs
            phpunit --log-junit test-results/phpunit/site-results.xml
            WP_MULTISITE=1 phpunit --log-junit test-results/phpunit/multisite-results.xml
      - store_test_results:
          path: test-results

  deploy_job: &deploy_job
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "16:da:86:fe:b2:e3:73:84:3b:04:e1:f6:1e:e0:93:a4"
      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install rsync
            pip install --user ansible
      - run:
          name: Build inventory
          command: |
            echo $HOSTNAME > ansible/hosts.ini
      - run:
          name: Run playbook
          environment:
            - ANSIBLE_HOST_KEY_CHECKING: False
          command: |
            ansible-playbook ansible/deploy.yml -i ansible/hosts.ini -u ${SSH_USER} -e ansible_port=${SSH_PORT} -e sitename=${<< parameters.sitename >>} -e workspace=${PWD}/ -v

jobs:
  php71-wp50-test:
    docker:
      - image: circleci/php:7.1
      - image: *mysql_image
    parameters:
      version:
        type: string
        default: "5.0"
    <<: *test_job
  php73-wp51-test:
    docker:
      - image: circleci/php:7.3
      - image: *mysql_image
    parameters:
      version:
        type: string
        default: "5.1"
    <<: *test_job
  php73-wp52-test:
    docker:
      - image: circleci/php:7.3
      - image: *mysql_image
    parameters:
      version:
        type: string
        default: "5.2"
    <<: *test_job
  php73-wp53-test:
    docker:
      - image: circleci/php:7.3
      - image: *mysql_image
    parameters:
      version:
        type: string
        default: "5.3"
    <<: *test_job

  deploy_dev:
    executor:
      name: deploy
    parameters:
      sitename:
        type: env_var_name
        default: SITENAME_DEV
    <<: *deploy_job

  deploy_prd:
    executor:
      name: deploy
    parameters:
      sitename:
        type: env_var_name
        default: SITENAME_PRD
    <<: *deploy_job

workflows:
  version: 2
  deployment:
    jobs:
      # - php71-wp50-test
      - php73-wp51-test
      - php73-wp52-test
      - php73-wp53-test
      - deploy_dev:
          requires:
            # - php71-wp50-test
            - php73-wp51-test
            - php73-wp52-test
            - php73-wp53-test
          filters:
            branches:
              ignore:
                - master
      - deploy_prd:
          requires:
            # - php71-wp50-test
            - php73-wp51-test
            - php73-wp52-test
            - php73-wp53-test
          filters:
            branches:
              only:
                - master
