---
ansible_ssh_private_key_file: ~/.ssh/id_rsa

excludes_file: "{{ playbook_dir }}/.rsyncignore"

wp_root_dir: "/var/vhosts/{{ sitename }}/www"
wp_theme_dir: "{{ wp_root_dir }}/wp-content/themes"

theme_name: wp-gatsby-theme
theme_dir: "{{ wp_theme_dir }}/{{ theme_name }}"
